parameters:
#    futur_planning.example.class: Futur\PlanningBundle\Example

services:
#    futur_planning.example:
#        class: %futur_planning.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
