parameters:
#    futur_ticket.example.class: Futur\TicketBundle\Example

services:
#    futur_ticket.example:
#        class: %futur_ticket.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
