imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

framework:
    #esi:             ~
    translator:      { fallback: "%locale%" }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver, add the path in parameters.yml
        # e.g. database_path: "%kernel.root_dir%/data/data.db3"
        # path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        default_entity_manager: default
        resolve_target_entities:
            Symfony\Component\Security\Core\User\UserInterface: Futur\UserBundle\Entity\User
        entity_managers:
            default:
                mappings:
                    FuturTicketBundle: ~
                    FuturAdminBundle: ~
                    FOSUserBundle: ~
                    FuturModuleBundle: ~
                    FuturSujetBundle: ~
                    FuturPlanningBundle: ~
                    FuturNoteBundle: ~
                    FuturCoursBundle: ~
                    FuturUserBundle:
                        mapping:              true
                        type:                 annotation
                        alias:                ~
                        prefix:               Futur\UserBundle\Entity
                        is_bundle:            true
                    CCDNForumForumBundle:
                        mapping:              true
                        type:                 yml
                        dir:                  "Resources/config/doctrine"
                        alias:                ~
                        prefix:               CCDNForum\ForumBundle\Entity
                        is_bundle:            true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

fos_user:
    db_driver:     orm                        # Le type de BDD à utiliser, nous utilisons l'ORM Doctrine depuis le début
    firewall_name: main                       # Le nom du firewall derrière lequel on utilisera ces utilisateurs
    user_class:    Futur\UserBundle\Entity\User

fr3d_ldap:
    driver:
        host:                ldap.42.fr
        port:                389
        username:            uid=apetit,ou=2013,ou=people,dc=42,dc=fr
        password:            6kdVDjc6
        bindRequiresDn:      true
        baseDn:              dc=42,dc=fr
#        accountFilterFormat: (&(uid=%s)) # Optional. sprintf format %s will be the username
#        optReferrals:        false  # Optional
#        useSsl:              true   # Enable SSL negotiation. Optional
#        useStartTls:         true   # Enable TLS negotiation. Optional
    user:
        baseDn: dc=42,dc=fr
        filter: (&(ObjectClass=ft-user))
        attributes:          # Specify ldap attributes mapping [ldap attribute, user object method]
           - { ldap_attr: uid,  user_method: setUsername }
           - { ldap_attr: alias,   user_method: setEmail }
           - { ldap_attr: cn,  user_method: setCn }
           - { ldap_attr: first-name,  user_method: setFirstName }
           - { ldap_attr: last-name,  user_method: setLastName }
           #- { ldap_attr: birth-date,  user_method: setBirthDate }
           - { ldap_attr: mobile-phone,  user_method: setMobilePhone }
           #- { ldap_attr: city,  user_method: setCity }
           #- { ldap_attr: postal-code,  user_method: setPostalCode }
           #- { ldap_attr: nationality,  user_method: setNationality }
           #- { ldap_attr: country,  user_method: setCountry }
           #- { ldap_attr: degree,  user_method: setDegree }
    service:
#        user_manager: fos_user.user_manager          # Overrides default user manager
        ldap_manager: fr3d_ldap.ldap_manager.default # Overrides default ldap manager
