parameters:
#    futur_note.example.class: Futur\NoteBundle\Example

services:
#    futur_note.example:
#        class: %futur_note.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
