<?php

namespace Futur\CoursBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ActiviteCoursRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ActiviteCoursRepository extends EntityRepository
{
}
