parameters:
#    futur_cours.example.class: Futur\CoursBundle\Example

services:
#    futur_cours.example:
#        class: %futur_cours.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
