parameters:
#    futur_fofo.example.class: Futur\FofoBundle\Example

services:
#    futur_fofo.example:
#        class: %futur_fofo.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
