<?php

namespace Futur\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CorrigeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CorrigeRepository extends EntityRepository
{
}
