<?php

namespace Futur\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CorrecteurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CorrecteurRepository extends EntityRepository
{
}
